[workspace]
members = [
    "senra_api",
    "senra_app",
    "senra_client",
    "senra_server"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Sieluna <seele.peng@gmail.com>"]
edition = "2024"
repository = "https://github.com/Sieluna/ShaderLab"

[workspace.dependencies]
http = { version = "1", default-features = false }
senra_api = { path = "senra_api", default-features = false }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }
thiserror = { version = "2", default-features = false }
time = { version = "0.3", default-features = false }
tokio = { version = "1", default-features = false }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false }
utoipa = { version = "5", default-features = false }
