[package]
name = "senra_api"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
postcard = { version = "1", default-features = false, features = ["alloc"] }
serde = { workspace = true, features = ["derive", "alloc"] }
serde_json = { workspace = true, features = ["alloc"] }
thiserror.workspace = true
time = { workspace = true, features = ["alloc", "formatting", "parsing", "serde"] }
utoipa = { workspace = true, features = ["macros", "time"], optional = true }

[features]
default = ["std"]
std = ["serde/std", "serde_json/std", "thiserror/std", "time/std"]
docs = ["dep:utoipa", "std"]
