[package]
name = "senra_api"
version = "0.1.0"
edition = "2024"

[dependencies]
http.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
utoipa = { workspace = true, optional = true }

[features]
default = []
docs = ["dep:utoipa"]
