[package]
name = "shaderlab-client"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13", features = ["tokio"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
